# Generated by Django 5.1 on 2024-08-29 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanckAccount',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, default=None, max_length=65, verbose_name='card_number')),
                ('payment_day', models.IntegerField()),
                ('id_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_account.banckaccount')),
            ],
        ),
    ]
