# Generated by Django 5.1 on 2024-08-30 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65, verbose_name='Titulo')),
                ('id_titular_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Bank account',
            },
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, default=None, max_length=65, verbose_name='Numero cartão')),
                ('payment_day', models.IntegerField(verbose_name='Dia vencimento')),
                ('id_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='bank_account.bankaccountmodel', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Card',
            },
        ),
    ]
