# Generated by Django 5.1 on 2024-08-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BanckAccount',
            new_name='BankAccount',
        ),
    ]
