# Generated by Django 5.1 on 2024-08-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_rename_banckaccount_bankaccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankAccount',
            new_name='BankAccountModel',
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, default=None, max_length=65, verbose_name='card_number')),
                ('payment_day', models.IntegerField(verbose_name='Payment day')),
                ('id_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_account.bankaccountmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
