# Generated by Django 5.1 on 2024-08-30 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_alter_cardmodel_id_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='id_bank_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cartoes', to='bank_account.bankaccountmodel', verbose_name='Banco'),
        ),
    ]
