# Generated by Django 5.1 on 2024-08-30 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0003_rename_bankaccount_bankaccountmodel_cardmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccountmodel',
            options={'verbose_name': 'Bank account'},
        ),
        migrations.AlterModelOptions(
            name='cardmodel',
            options={'verbose_name': 'Card'},
        ),
        migrations.AddField(
            model_name='bankaccountmodel',
            name='id_titular_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='bankaccountmodel',
            name='title',
            field=models.CharField(max_length=65, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='card_number',
            field=models.CharField(blank=True, default=None, max_length=65, verbose_name='Numero cartão'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='payment_day',
            field=models.IntegerField(verbose_name='Data vencimento'),
        ),
    ]
