# Generated by Django 5.1 on 2024-08-31 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0003_alter_cardmodel_id_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='turn_day',
            field=models.IntegerField(default=30, verbose_name='Dia que vira'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='id_bank_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='bank_account.bankaccountmodel', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='payment_day',
            field=models.IntegerField(default=5, verbose_name='Dia vencimento'),
        ),
    ]
