# Generated by Django 5.1 on 2024-09-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0004_cardmodel_turn_day_alter_cardmodel_id_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
