# Generated by Django 5.1 on 2024-08-30 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0004_alter_bankaccountmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='id_bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='bank_account.bankaccountmodel', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='payment_day',
            field=models.IntegerField(verbose_name='Dia vencimento'),
        ),
    ]
