# Generated by Django 5.1 on 2024-09-03 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0005_cardmodel_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='card_number',
            field=models.CharField(max_length=65, verbose_name='Nome do cartão'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='id_bank_account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='bank_account.bankaccountmodel', verbose_name='Banco'),
        ),
    ]
