# Generated by Django 5.1 on 2024-09-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0006_alter_cardmodel_card_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardmodel',
            old_name='card_number',
            new_name='card_name',
        ),
    ]
