# Generated by Django 5.1 on 2024-08-17 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='InstituicaoFincanceira',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=65)),
            ],
            options={
                'verbose_name': 'Instituição Financeira',
                'verbose_name_plural': 'Instituições Financeiras',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=65)),
                ('descricao', models.CharField(max_length=165, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('data', models.DateTimeField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('valor', models.PositiveIntegerField()),
                ('compartilhado', models.BooleanField(default=False)),
                ('fixo_mensal', models.BooleanField(default=False)),
                ('quantidade_parcelas', models.PositiveIntegerField(default=1)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.categoria')),
                ('id_instituicao_financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.instituicaofincanceira')),
                ('id_usuario_ativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_to_usuario_ativo', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_titular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_to_usuario_titular', to=settings.AUTH_USER_MODEL)),
                ('id_modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.modalidade')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.tipo')),
            ],
            options={
                'verbose_name': 'Lançamento',
            },
        ),
        migrations.CreateModel(
            name='LancamentoBaixa',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('valor', models.PositiveIntegerField()),
                ('numero_parcela', models.PositiveIntegerField(default=1)),
                ('id_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.lancamento')),
            ],
            options={
                'verbose_name': 'Lançamento Baixa',
                'verbose_name_plural': 'Lançamentos Baixas',
            },
        ),
    ]
