# Generated by Django 5.1 on 2024-08-30 22:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65, verbose_name='Titulo')),
                ('description', models.CharField(blank=True, default=None, max_length=165, null=True)),
                ('value', models.FloatField(verbose_name='Valor')),
                ('slug', models.SlugField(unique=True)),
                ('entry_date', models.DateField(default=datetime.date(2024, 8, 30), null=True, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared', models.BooleanField(default=False)),
                ('fixed', models.BooleanField(default=False)),
                ('installments_number', models.PositiveIntegerField(default=1, verbose_name='Quantidade de parcelas')),
                ('id_active_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_to_usuario_ativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario ativo')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.category', verbose_name='Categoria')),
                ('id_titular_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_to_usuario_titular', to=settings.AUTH_USER_MODEL, verbose_name='Titular')),
                ('id_modality', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lancamentos.modality', verbose_name='Modalidade')),
                ('id_type', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='lancamentos.type', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'ordering': ['-entry_date'],
            },
        ),
    ]
