# Generated by Django 5.1 on 2024-08-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lancamentobaixa',
            name='valor',
            field=models.FloatField(),
        ),
    ]
