# Generated by Django 5.1 on 2024-08-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=165, null=True, verbose_name='Descrição'),
        ),
    ]
