# Generated by Django 5.1 on 2024-08-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0002_alter_lancamento_valor_alter_lancamentobaixa_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='descricao',
            field=models.CharField(default=None, max_length=165, null=True),
        ),
    ]
