# Generated by Django 5.1 on 2024-08-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0003_alter_lancamento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='data',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='slug',
            field=models.SlugField(),
        ),
    ]
