# Generated by Django 5.1 on 2024-08-30 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_alter_cardmodel_id_bank_account'),
        ('lancamentos', '0003_entry_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='Fixo'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id_card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_account.cardmodel', verbose_name='Cartao'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='shared',
            field=models.BooleanField(default=False, verbose_name='Compartilhado'),
        ),
    ]
