# Generated by Django 5.1 on 2024-08-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0004_alter_lancamento_data_alter_lancamento_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamento',
            old_name='data',
            new_name='data_lancamento',
        ),
        migrations.RenameField(
            model_name='lancamento',
            old_name='valor',
            new_name='valor_total',
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('numero_parcela', models.PositiveIntegerField()),
                ('valor_parcela', models.FloatField()),
                ('data_vencimento', models.DateField()),
                ('id_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.lancamento')),
            ],
        ),
    ]
