# Generated by Django 5.1 on 2024-08-30 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0003_alter_cardmodel_id_bank_account'),
        ('lancamentos', '0004_alter_entry_fixed_alter_entry_id_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='id_bank_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bank_account.bankaccountmodel'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id_card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bank_account.cardmodel', verbose_name='Cartao'),
        ),
    ]
