# Generated by Django 5.1 on 2024-08-31 13:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0003_alter_cardmodel_id_bank_account'),
        ('lancamentos', '0005_entry_id_bank_account_alter_entry_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 8, 31), null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id_bank_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bank_account.bankaccountmodel', verbose_name='Banco'),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('numero_parcela', models.PositiveIntegerField()),
                ('valor_parcela', models.FloatField()),
                ('data_vencimento', models.DateField()),
                ('id_lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.entry')),
            ],
        ),
    ]
