# Generated by Django 5.1 on 2024-08-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0005_rename_data_lancamento_data_lancamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='data_lancamento',
            field=models.DateField(default=None, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_instituicao_financeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.instituicaofincanceira', verbose_name='Instituição financeira'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.modalidade', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.tipo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de parcelas'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='valor_total',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.PositiveIntegerField()),
                ('telefone', models.PositiveIntegerField(default=None, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_usuario_ativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_to_usuario_ativo', to='lancamentos.usuario'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_usuario_titular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_to_usuario_titular', to='lancamentos.usuario', verbose_name='Titular'),
        ),
    ]
