# Generated by Django 5.1 on 2024-08-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0006_alter_entry_entry_date_alter_entry_id_bank_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='data_vencimento',
            new_name='due_day',
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='id_lancamento',
            new_name='id_entry',
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='numero_parcela',
            new_name='installment_number',
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='valor_parcela',
            new_name='installment_value',
        ),
    ]
