# Generated by Django 5.1 on 2024-08-20 01:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0006_alter_lancamento_data_lancamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='id_usuario_ativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_to_usuario_ativo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_usuario_titular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_to_usuario_titular', to=settings.AUTH_USER_MODEL, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='data_lancamento',
            field=models.DateField(default=datetime.date(2024, 8, 19), null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='descricao',
            field=models.CharField(blank=True, default=None, max_length=165, null=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_modalidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lancamentos.modalidade', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='lancamentos.tipo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
