# Generated by Django 5.1 on 2024-08-29 16:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0007_alter_lancamento_id_usuario_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='instituicaofincanceira',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-data_lancamento'], 'verbose_name': 'Lançamento'},
        ),
        migrations.AlterModelOptions(
            name='modalidade',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='instituicaofincanceira',
            old_name='nome',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='lancamentobaixa',
            old_name='id_lancamento',
            new_name='id_parcela',
        ),
        migrations.RenameField(
            model_name='modalidade',
            old_name='nome',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='nome',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='data_lancamento',
            field=models.DateField(default=datetime.date(2024, 8, 29), null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='id_usuario_ativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_to_usuario_ativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario ativo'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='titulo',
            field=models.CharField(max_length=65, verbose_name='Titulo'),
        ),
    ]
