# Generated by Django 5.1 on 2024-08-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0007_rename_data_vencimento_installment_due_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='due_day',
            new_name='due_date',
        ),
    ]
