# Generated by Django 5.1 on 2024-08-31 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0004_cardmodel_turn_day_alter_cardmodel_id_bank_account_and_more'),
        ('lancamentos', '0008_rename_due_day_installment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id_card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_account.cardmodel', verbose_name='Cartao'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(verbose_name='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='id_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.entry', verbose_name='Lancamento'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.PositiveIntegerField(verbose_name='Numero parcela'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_value',
            field=models.FloatField(verbose_name='Valor parcela'),
        ),
    ]
