# Generated by Django 5.1 on 2024-08-30 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0008_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='data_lancamento',
            field=models.DateField(default=datetime.date(2024, 8, 30), null=True, verbose_name='Data'),
        ),
    ]
