# Generated by Django 5.1 on 2024-08-31 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0009_alter_entry_id_card_alter_installment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lancamentos.category', verbose_name='Categoria'),
        ),
    ]
