# Generated by Django 5.1 on 2024-09-01 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0010_alter_entry_id_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='installment_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='installment_value',
            new_name='value',
        ),
    ]
