# Generated by Django 5.1 on 2024-09-01 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0011_rename_installment_number_installment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 9, 1), null=True, verbose_name='Data'),
        ),
    ]
