# Generated by Django 5.1 on 2024-09-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0012_alter_entry_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('id_installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancamentos.entry')),
            ],
            options={
                'verbose_name': 'Lançamento Baixa',
                'verbose_name_plural': 'Lançamentos Baixas',
            },
        ),
    ]
