# Generated by Django 5.1 on 2024-09-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='id_payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lancamentos.payment', verbose_name='Pagamento'),
        ),
    ]
