# Generated by Django 5.1 on 2024-09-01 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0016_alter_installment_id_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id_installment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lancamentos.entry'),
        ),
    ]
