# Generated by Django 5.1 on 2024-09-01 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0017_alter_payment_id_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='id_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lancamentos.entry', verbose_name='Lancamento'),
        ),
    ]
