# Generated by Django 5.1 on 2024-09-03 01:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0006_alter_cardmodel_card_number_and_more'),
        ('lancamentos', '0019_payment_id_active_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='id_payment',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 9, 2), null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id_bank_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_account.bankaccountmodel', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id_installment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lancamentos.installment'),
        ),
    ]
