# Generated by Django 5.1 on 2024-09-04 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0020_remove_installment_id_payment_alter_entry_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 9, 3), null=True, verbose_name='Data'),
        ),
    ]
