# Generated by Django 5.1 on 2024-09-05 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0021_alter_payment_options_alter_entry_entry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='due_date',
            new_name='payment_day',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 9, 5), null=True, verbose_name='Data'),
        ),
    ]
