# Generated by Django 5.1 on 2024-09-08 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0022_rename_due_date_installment_payment_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 9, 7), null=True, verbose_name='Data'),
        ),
    ]
