# Generated by Django 5.1 on 2024-09-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0023_alter_entry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paga'),
        ),
    ]
