# Generated by Django 5.1 on 2024-09-08 15:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0025_rename_payment_day_installment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2024, 9, 8), null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='id_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='lancamentos.entry', verbose_name='Lancamento'),
        ),
    ]
