from .entry_views.func_views import *
from .entry_views.new_entry_view import NewEntryView
from .entry_views.entry_delete_view import EntryDeleteView
from .entry_views.entries_view import EntriesView
from .entry_views.entry_view import EntryView
from .entry_views.entry_update_view import EntryUpdateView
from .installment_views.create_installment_view import InstallmentCreateView
from .installment_views.installment_list_view import InstallmentListView
from .installment_views.pay_installment_view import PayInstallmentView
